-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ · 微信 zhuatech / zhuatech2
-- 仅创建结构，不初始化虚构会议或共享账号。
create table meeting (id bigint auto_increment primary key, department_id bigint not null, host_id bigint not null, title varchar(120) not null, category varchar(60) not null, agenda varchar(2000) not null, status varchar(20) not null, scheduled_at timestamp(6) not null, created_at timestamp(6) not null, started_at timestamp(6), ended_at timestamp(6), capacity int not null, duration_minutes int not null, version bigint not null, generation bigint not null, locked boolean not null, chat_enabled boolean not null, foreign key(department_id) references department(id), foreign key(host_id) references account(id), check(capacity between 2 and 32), check(duration_minutes between 15 and 480));
create index meeting_scope on meeting(department_id,status,scheduled_at);
create table attendee (id bigint auto_increment primary key, meeting_id bigint not null, account_id bigint, display_name varchar(120) not null, status varchar(20) not null, guest_key varchar(64) unique, requested_at timestamp(6) not null, admitted_at timestamp(6), left_at timestamp(6), expires_at timestamp(6), can_speak boolean not null, hand_raised boolean not null, foreign key(meeting_id) references meeting(id), foreign key(account_id) references account(id), unique(meeting_id,account_id));
create index attendee_status on attendee(meeting_id,status);
create table invitation (id bigint auto_increment primary key, meeting_id bigint not null, token_hash varchar(64) not null unique, expires_at timestamp(6) not null, max_uses int not null, uses int not null, revoked boolean not null, foreign key(meeting_id) references meeting(id), check(uses between 0 and max_uses));
create table meeting_message (id bigint auto_increment primary key, meeting_id bigint not null, attendee_id bigint not null, nonce varchar(40) not null, content varchar(4000) not null, created_at timestamp(6) not null, removed boolean not null, foreign key(meeting_id) references meeting(id), foreign key(attendee_id) references attendee(id), unique(meeting_id,attendee_id,nonce));
create index meeting_message_history on meeting_message(meeting_id,id);
create table media_lease (id bigint auto_increment primary key, meeting_id bigint not null, attendee_id bigint not null, identity varchar(100) not null unique, physical_room varchar(100) not null, end_reason varchar(40), credential varchar(64) not null, session_key varchar(64) not null, issued_at timestamp(6) not null, connected_at timestamp(6), disconnected_at timestamp(6), revoked boolean not null, applied_speak boolean not null, foreign key(meeting_id) references meeting(id), foreign key(attendee_id) references attendee(id));
create index media_lease_active on media_lease(meeting_id,revoked,disconnected_at);
